import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { removeTemporaryRoots, temporaryRoot } from "./temporary-roots.js";
import { DurableOwnershipStore, MemoryOwnershipStore, type OwnershipRecord, type OwnershipStore } from "../src/setup-ownership.js";
import { SetupOrchestrator, type SetupClientAdapter, type SetupDoctor } from "../src/setup.js";
import type { SetupTarget } from "../src/setup-result.js";
import { currentSetupPlatform } from "../src/setup-platform.js";

afterAll(removeTemporaryRoots);

const target: SetupTarget = { client: "codex", scope: "user", alias: "pi-session-mcp" };
const fingerprint = "a".repeat(64);
function fixture(options: { state?: "absent" | "equivalent" | "divergent"; doctor?: SetupDoctor; ownership?: OwnershipStore } = {}) {
  let state = options.state ?? "absent"; let applyCalls = 0; let removeCalls = 0; let verifyCalls = 0;
  const adapter: SetupClientAdapter = { name: "codex", supportedScopes: ["user"], async inspect() { return state === "absent" ? { state } : { state, fingerprint }; }, async apply() { applyCalls += 1; state = "equivalent"; }, async remove() { removeCalls += 1; state = "absent"; }, async verify() { verifyCalls += 1; return { ok: state === "equivalent", code: state === "equivalent" ? "verified" : "not_registered" }; } };
  const orchestrator = new SetupOrchestrator({ adapters: [adapter], ...(options.doctor ? { doctor: options.doctor } : {}), ownership: options.ownership ?? new MemoryOwnershipStore(), intendedFingerprint: fingerprint });
  return { adapter, orchestrator, get state() { return state; }, get applyCalls() { return applyCalls; }, get removeCalls() { return removeCalls; }, get verifyCalls() { return verifyCalls; } };
}

describe("setup lifecycle", () => {
  it("defaults to a non-mutating dry-run", async () => { const f = fixture(); const output = await f.orchestrator.run({ targets: [target] }); expect(output).toMatchObject({ operation: "dry-run", status: "planned", exitCode: 0 }); expect(output.findings[0]).toMatchObject({ status: "absent", code: "absent" }); expect(f.applyCalls).toBe(0); });
  it("fails closed when Doctor fails and does not mutate on dry-run or apply", async () => { const f = fixture({ doctor: { async check() { return { ok: false, code: "doctor_failed" }; } } }); expect((await f.orchestrator.run({ targets: [target] })).status).toBe("failed"); expect((await f.orchestrator.run({ operation: "apply", targets: [target] })).status).toBe("failed"); expect(f.applyCalls).toBe(0); });
  it("reports unsupported configured targets without invoking an adapter", async () => { const f = fixture(); const output = await f.orchestrator.run({ operation: "apply", targets: [{ client: "claude-code", scope: "project", alias: "pi-session-mcp" }] }); expect(output.findings[0]).toMatchObject({ status: "unsupported", code: "client_unsupported" }); expect(f.applyCalls).toBe(0); });
  it("reports divergent registrations and never replaces them", async () => { const f = fixture({ state: "divergent" }); const output = await f.orchestrator.run({ operation: "apply", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "divergent", code: "divergence_requires_replacement" }); expect(f.applyCalls).toBe(0); });
  it("rejects malformed targets before any adapter mutation", async () => { const f = fixture(); const output = await f.orchestrator.run({ operation: "apply", targets: [{ client: "../secret", scope: "user", alias: "pi-session-mcp" }] }); expect(output).toMatchObject({ status: "failed", exitCode: 1 }); expect(output.findings[0]?.code).toBe("target_invalid"); expect(f.applyCalls).toBe(0); });
  it("applies idempotently and does not call apply for equivalent state", async () => { const f = fixture(); expect((await f.orchestrator.run({ operation: "apply", targets: [target] })).findings[0]?.code).toBe("applied"); expect((await f.orchestrator.run({ operation: "apply", targets: [target] })).findings[0]?.code).toBe("already_equivalent"); expect(f.applyCalls).toBe(1); });
  it("recovers pending ownership when registration is equivalent", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint, previous: "absent", phase: "pending", transactionId: "tx-1" }); const f = fixture({ state: "equivalent", ownership }); const output = await f.orchestrator.run({ operation: "apply", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "ok", code: "pending_recovered" }); expect((await ownership.get(target))?.phase).toBe("owned"); expect(f.applyCalls).toBe(0); });
  it("fails apply and verify closed when owned state belongs to another release", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint: "b".repeat(64), previous: "absent", phase: "owned", transactionId: "tx-old-release" }); const f = fixture({ state: "equivalent", ownership }); for (const operation of ["apply", "verify"] as const) { const output = await f.orchestrator.run({ operation, targets: [target] }); expect(output).toMatchObject({ status: "failed", exitCode: 1 }); expect(output.findings[0]).toMatchObject({ code: "release_binding_mismatch" }); } expect(f.applyCalls).toBe(0); expect(f.verifyCalls).toBe(0); });
  it("does not recreate an externally deleted owned registration", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint, previous: "absent", phase: "owned", transactionId: "tx-deleted" }); const f = fixture({ state: "absent", ownership }); const output = await f.orchestrator.run({ operation: "apply", targets: [target] }); expect(output).toMatchObject({ status: "failed", exitCode: 1 }); expect(output.findings[0]).toMatchObject({ code: "ownership_diverged" }); expect(f.applyCalls).toBe(0); });
  it("does not bypass a changed release when its owned registration is absent", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint: "b".repeat(64), previous: "absent", phase: "owned", transactionId: "tx-old-deleted" }); const f = fixture({ state: "absent", ownership }); const output = await f.orchestrator.run({ operation: "apply", targets: [target] }); expect(output).toMatchObject({ status: "failed", exitCode: 1 }); expect(output.findings[0]).toMatchObject({ code: "release_binding_mismatch" }); expect(f.applyCalls).toBe(0); });
  it("retries a pending ownership transaction when registration is absent", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint, previous: "absent", phase: "pending", transactionId: "tx-2" }); const f = fixture({ ownership }); expect((await f.orchestrator.run({ operation: "apply", targets: [target] })).findings[0]?.code).toBe("applied"); expect((await ownership.get(target))?.phase).toBe("owned"); });
  it("keeps ownership pending when post-apply inspection mismatches", async () => { const ownership = new MemoryOwnershipStore(); const f = fixture({ ownership }); const original = f.adapter.inspect; let inspections = 0; f.adapter.inspect = async (...args) => { inspections += 1; return inspections > 2 ? { state: "divergent" } : original(...args); }; const output = await f.orchestrator.run({ operation: "apply", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "failed", code: "apply_failed_recovery_pending" }); expect((await ownership.get(target))?.phase).toBe("pending"); });
  it("cleans up a pending transaction during rollback when registration is equivalent", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint, previous: "absent", phase: "pending", transactionId: "tx-pending" }); const f = fixture({ state: "equivalent", ownership }); const output = await f.orchestrator.run({ operation: "rollback", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "ok", code: "rolled_back" }); expect(await ownership.get(target)).toBeUndefined(); expect(f.removeCalls).toBe(1); });
  it("removes pending ownership without a client mutation when registration is already absent", async () => { const ownership = new MemoryOwnershipStore(); await ownership.put({ target, fingerprint, previous: "absent", phase: "pending", transactionId: "tx-absent" }); const f = fixture({ state: "absent", ownership }); const output = await f.orchestrator.run({ operation: "remove", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "ok", code: "removed" }); expect(await ownership.get(target)).toBeUndefined(); expect(f.removeCalls).toBe(0); });
  it("fails verify and cleanup for an unknown client before adapter/report reflection", async () => { const f = fixture(); for (const operation of ["verify", "remove"] as const) { const output = await f.orchestrator.run({ operation, targets: [{ client: "unknown", scope: "user", alias: "pi-session-mcp" }] }); expect(output.exitCode).toBe(1); expect(output.findings[0]).toMatchObject({ status: "failed", code: "target_invalid" }); } });
  it.skipIf(!currentSetupPlatform())("fails closed on corrupt durable ownership data without exposing its path", async () => { const dir = await temporaryRoot("pi-session-mcp-ownership-"); const path = join(dir, "ownership.json"); await writeFile(path, "{not-json", { mode: 0o600 }); const f = fixture({ ownership: new DurableOwnershipStore(path) }); const output = await f.orchestrator.run({ operation: "remove", targets: [target] }); expect(output.status).toBe("failed"); expect(JSON.stringify(output)).not.toContain(path); });
  it("does not remove owned state after an external divergent change", async () => { const f = fixture(); await f.orchestrator.run({ operation: "apply", targets: [target] }); f.adapter.inspect = async () => ({ state: "divergent", fingerprint: "b".repeat(64) }); const output = await f.orchestrator.run({ operation: "remove", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "failed", code: "ownership_diverged" }); expect(f.removeCalls).toBe(0); });
  it("removes owned state and verifies post-remove absence", async () => { const f = fixture(); await f.orchestrator.run({ operation: "apply", targets: [target] }); const output = await f.orchestrator.run({ operation: "remove", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "ok", code: "removed" }); expect(f.removeCalls).toBe(1); });
  it("fails cleanup when post-remove inspection remains equivalent", async () => { const f = fixture(); await f.orchestrator.run({ operation: "apply", targets: [target] }); f.adapter.remove = async () => { f.adapter.inspect = async () => ({ state: "equivalent", fingerprint }); }; const output = await f.orchestrator.run({ operation: "remove", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "failed", code: "cleanup_failed" }); });
  it("invokes verifier and projects verifier failures", async () => { const f = fixture(); await f.orchestrator.run({ operation: "apply", targets: [target] }); f.adapter.verify = async () => ({ ok: false, code: "mcp_timeout" }); const output = await f.orchestrator.run({ operation: "verify", targets: [target] }); expect(output.findings[0]).toMatchObject({ status: "failed", code: "mcp_timeout" }); expect(f.verifyCalls).toBe(0); });
  it("stops client mutation when ownership is compromised after pending state", async () => {
    let puts = 0;
    let pending: OwnershipRecord | undefined;
    const ownership: OwnershipStore = {
      async get() { return pending; },
      async put(record) { puts += 1; pending = record; },
      async delete() { pending = undefined; },
      assertHealthy() { if (puts > 0) throw new Error("ownership_lock_compromised"); },
      async transaction(operation) {
        return operation(this);
      },
    };
    const f = fixture({ ownership });
    const output = await f.orchestrator.run({ operation: "apply", targets: [target] });
    expect(output.findings[0]).toMatchObject({ status: "failed", code: "apply_failed_recovery_pending" });
    expect(f.applyCalls).toBe(0);
    expect(pending?.phase).toBe("pending");
  });
});
